services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_NUM_CTX=8192
    volumes:
      - ollama_data:/root/.ollama
    entrypoint: >
      bash -c "
        ollama serve &
        sleep 10 &&
        echo '' | ollama run llama3 &&
        wait
      "
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:11434/api/tags"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  ollama_data:
